name: Node.js CI

on:
  push:
    branches: [master,release]
  pull_request:
    branches: [master,release]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Rollup template

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm@6.32.18
      - name: Install 
        run: |
          pnpm install --frozen-lockfile=false
      - name: Test
        run: |
          pnpm test --filter=./packages/cli